name: Deploy Laravel App to API VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up SSH Key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.PC_SSHKEY_PRIVATE}}

      - name: Deploy to Staging Server
        run: |
          ssh -o StrictHostKeyChecking=no sdssn-api@${{ secrets.SSH_HOST_IP }} << 'EOF'
            cd htdocs/api.sdssn.org/sdssnapp
            git fetch origin
            git reset --hard origin/main
            git clean -f
            # export COMPOSER_ALLOW_SUPERUSER=1; composer show;
            composer install  # Install dependencies
            php artisan migrate --force  # Migrate the database
            php artisan cache:clear  # Clear the cache
            php artisan view:clear  # Clear the view cache
            php artisan route:cache  # Clear the route cache
            php artisan optimize:clear # Clear the optimize cache
            npm install  # Install dependencies
            npm run build  # Build the Node app
          EOF