name: Deploy Laravel App to (PRO) VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up SSH Key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.PC_SSHKEY_PRIVATE}}

      - name: Deploy to Staging Server
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.PRO_SSH_USER }}@${{ secrets.SSH_HOST_IP }} << 'EOF'
            # /home/sdssn-pro/htdocs/pro.sdssn.org/sdssnapp
            # Navigate to the staging folder
            cd htdocs/pro.sdssn.org/sdssnapp
            git pull origin main

            composer install
            php artisan migrate
            php artisan optimize:clear

            npm install
            npm run build

          EOF