name: Deploy Laravel App to (PRO) VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up SSH Key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.PC_SSHKEY_PRIVATE}}

      - name: Deploy to Staging Server
        run: |
          ssh -o StrictHostKeyChecking=no sdssn-pro@${{ secrets.SSH_HOST_IP }} << 'EOF'
            cd htdocs/pro.sdssn.org

            git pull origin main  # Pull the latest changes from main branch

            composer install  # Install dependencies
            php artisan migrate --force  # Migrate the database
            php artisan cache:clear  # Clear the cache
            php artisan view:clear  # Clear the view cache
            php artisan route:cache  # Clear the route cache
            php artisan optimize:clear
            
            npm install  # Install dependencies
            npm run build  # Build the Node app
            echo "Deployment to Staging Server completed successfully!"
            exit 0
          EOF